spring:
  application:
    name: task

  datasource:
    url: jdbc:mysql://mysql:3306/task
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000
