name: Build & Deploy Spring + Angular App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'corretto'

#      - name: Backend Unit Tests
#        working-directory: Backend/task
#        run: mvn -B test --file pom.xml

      - name: Build Spring Boot App
        working-directory: Backend/task
        run: |
          mvn clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v2
        with:
          context: ./Backend
          file: ./Backend/task/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/task-manager:latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Angular Dependencies
        working-directory: ./Frontend/task
        run: npm install

      - name: Build Angular App
        working-directory: ./Frontend/task
        run: npm run build -- --configuration production

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v2
        with:
          context: ./Frontend/task
          file: ./Frontend/task/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/task-manager:latest
